### ISSUE TITLE
time.sleep uses real time instead of simulation time

### ISSUE THREAD

**Issue by antoinepetty** [srobo/competition-simulator#101]
time.sleep uses real time instead of simulation time. These are not the same, and as the simulator is being used, we should be using simulation time.

Quoted from https://studentrobotics.org/forum/viewtopic.php?f=10&t=89&p=340#p340

**Comment by PeterJCLaw** [comment]
Nasty, nasty thought -- we could patch `sys.path` so that `import time` returns something which _looks_ like the built-in `time` module, but isn't.

I really don't think that's a good idea though. I suggest we explore providing an API for sleeping with regards to the simulation.

**Comment by PeterJCLaw** [comment]
It might also be useful to distribute a linter configuration which bans the competitor code from importing the `time` module.
