### ISSUE TITLE
Robot "power" not disabled when game stops

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-simulator#111]
Currently the game over logic just causes the controller to exit, but fails to power off the robot. This means that it will keep doing whatever it was last doing at the end of the game.

While we _can_ pause the simulator, it is likely that we won't be able to pause it at perfectly the right time. It therefore seems likely that we'll end up with cases where robots end up doing stuff after the end of a match.

**Comment by RealOrangeOne** [comment]
I suspect the way to handle this is to restore the `make_safe` mechanism for boards I've seen used, and just make every board safe just before terminating the simulation
