### ISSUE TITLE
Robot has no attribute usbkey

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-simulator#118]
Not sure if this is an intentional difference from the SR API, though it would be an easy one to fix.

Some competitors use this to know where on the filesystem their config files (or similar) are.

**Comment by RealOrangeOne** [comment]
This likely won't play nice with #102, as the users code is mounted read-only.

**Comment by PeterJCLaw** [comment]
I'm not sure I understand why there's a conflict there?
If we need to document that the filesystem is read-only that's fine.

Does Firejail move the code at all, or does it keep the same apparent path? I suspect without this competitors will resort to hard-coding things which are unlikely to work.

**Comment by RealOrangeOne** [comment]
Firejail keeps the same code, so we're fine on that front. Documenting that the filesystem may be read-only in a competition environment would solve that issue, though.
