### ISSUE TITLE
Lighting effects

### ISSUE THREAD

**Issue by antoinepetty** [srobo/competition-simulator#17]
Lighting effects similar to the actual competition.

For example

- dark before the match starts
- brightly lit during match
- dark after match

**Comment by WillB97** [comment]
As a starting point for this, the illumination of the arena is set through a combination of the `luminosity` variables in both `TexturedBackground` and `TexturedBackgroundLight`. `TexturedBackgroundLight` controls how bright it is while `TexturedBackground` sets how dark the shadows are and how dark the overall arena gets.

For adding spotlights, the light needs to be inside a to move it to it's desired location.
```
Transform {
    translation 0.5 10 -3   # location the beam originates from
    children [
        SpotLight {
        attenuation 0 0 1
        beamWidth 0.05      # angle of the focused beam (radians)
        cutOffAngle 0.08    # angle of the unfocused beam (radians)
        direction 3 -20 -3  # vector the beam points along
        intensity 75        # initial brightness (attenuated by distance)
        castShadows TRUE
        }
    ]
}
```
