### ISSUE TITLE
Reload world causing seg fault when SWI code loaded

### ISSUE THREAD

**Issue by JennyLynnFletcher** [srobo/competition-simulator#176]

**Comment by RealOrangeOne** [comment]
This seems to be an issue in collaboration with something in the supervisor. Perhaps around it removing robots.

**Comment by JennyLynnFletcher** [comment]
Looks like it's caused by record_animation() in competition_supervisor.py

**Comment by PeterJCLaw** [comment]
@JennyLynnFletcher any idea if this is still an issue?
I'm suspecting it may not be because we're on a new version of the simulator now and we've changed how the supervisor works. Also we're not reloading the world anywhere.

**Comment by PeterJCLaw** [comment]
I'm going to close this as we've not seen anything like this recently and reloading the world isn't something we expect to do in normal operations at the competition.
It _may_ still be an issue, but without a reproduce it's hard to know and if it's not affecting us this doesn't seem worth keeping open. We can re-open this with more details if it reappears.
