### ISSUE TITLE
Validate and decrease timestep to reduce frequency of physics bugs

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-simulator#192]
After some testing, we're fairly sure that we can reduce the rate of physics bugs by reducing the timestep from 32ms (the default) to 16ms.

While we don't want to do this for SR2020 (as it would likely affect the behaviour of the current robots), we should do this at some point.

When doing this we should validate that it does have the desired effect. See also #206 for other mitigations.

**Comment by JennyLynnFletcher** [comment]
I would expect this change to significantly reduce the number of people able to run at 1.0x speed, so would be worth making ManualTimestepRobot as the default before reducing the basic timestep

**Comment by eljueves** [comment]
Just made a pull request for this

**Comment by PeterJCLaw** [comment]
We think https://github.com/srobo/competition-simulator/pull/230 sorted this another way.
