### ISSUE TITLE
Build SR2021 arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/competition-simulator#197]
The SR2021 game has a different arena to what we've seen in the past. We need to create a new model of the arena so that it fits the spec from the rules and looks great.

Note: we have a separate task for making the arena dynamic (see https://github.com/srobo/competition-simulator/issues/216).

**Comment by PeterJCLaw** [comment]
Depends on https://github.com/srobo/tasks/issues/620 and maybe https://github.com/srobo/tasks/issues/621.

**Comment by PeterJCLaw** [comment]
#225 did this
