### ISSUE TITLE
Add sounds to simulation

### ISSUE THREAD

**Issue by antoinepetty** [srobo/competition-simulator#20]
This should help the viewer understand what's happening but there's definitely potential for this to just be annoying

**Comment by PeterJCLaw** [comment]
Is this primarily aimed for development or competition?
In development I'd hope there are other things which the viewer (developer) has access to, notably step-wise debugging and robot logs.
In competition we have commentators who can provide more context for the viewer, so I'm not convinced that this would add much.

I propose that we close this as "won't fix" until we have a more compelling reason to add it.
