### ISSUE TITLE
Mitigate robot explosions

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-simulator#206]
- [ ] setting CFM to something like 1e-4
- [ ] running the simulation at 16 or 8 ms timesteps
- [ ] turn off `self_collision`

**Comment by PeterJCLaw** [comment]
@Adimote are you likely to get to doing this soon? If not, I was wondering whether this would make a good intro task for someone -- it feels like it's a relatively well defined task.

**Comment by PeterJCLaw** [comment]
I believe we think this is now sorted?
Specifically, https://github.com/srobo/competition-simulator/pull/230 replaced #215.
Calling this done for now. We can re-open or have a new issue if it reappears.
