### ISSUE TITLE
Upgrade distance sensors to sonar

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-simulator#218]
I think the DistanceSensors are defaulting to infra-red sensors, hence why the max distance is 30cm, and there's 0 tolerance.

We can upgrade them if we just add to the root of DistanceSensor the property: `type "sonar"` and update the lookup table to go up to maybe 4m.

Some other properties migth need updating too, like `numberOfRays`

Here's a sample distance sensor that does this:

https://github.com/cyberbotics/webots/blob/d019ad4906e44a34a94fbea4e110d71af7172c07/projects/robots/k-team/khepera3/protos/Khepera3_USSensor.proto

**Comment by PeterJCLaw** [comment]
Looks like this happened in 061298d?

**Comment by WillB97** [comment]
This has happen although the docs update has not yet been merged
