### ISSUE TITLE
Edges of the floor are causing issues with wheel collision

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-simulator#227]

**Comment by PeterJCLaw** [comment]
Is this still an issue? https://github.com/srobo/competition-simulator/pull/230 fixed a bunch of things -- any chance it fixed this too?

**Comment by PeterJCLaw** [comment]
The arena itself was fully rebuilt in #260.
I'm going to close this as we don't seem to have a reproduction of the issue. However if it reappears we can open this again.
