### ISSUE TITLE
Competition simulation runs at real-time

### ISSUE THREAD

**Issue by WillB97** [srobo/competition-simulator#245]
Is there a reason that the competition supervisor runs the simulation at real-time speed when both the recording and animation are recorded independent of the simulation speed?

It is possible that this is a hold over from before we were using a basic timestep robots. If this is the case using the 'run' simulation speed would allow the simulations to complete faster.

**Comment by PeterJCLaw** [comment]
> It is possible that this is a hold over from before we were using a basic timestep robots. If this is the case using the 'run' simulation speed would allow the simulations to complete faster.

I'm pretty sure this is the reason -- I don't think we've explicitly thought about this. If we can run the competition simulations faster now, then :+1: to doing that.

There might be a small number of teams who have `time.something` in their code, however the docs are clear that that's not a reliable approach.
