### ISSUE TITLE
Re-use of DistanceSensor

### ISSUE THREAD

**Issue by WillB97** [srobo/competition-simulator#250]
Since DistanceSensor exists in the webots API we should rename the class in ruggeduino_devices to avoid name clashes.
The current suggestion is SonarSensor, since this class is only used within ruggeduino_devices and ruggeduino a change of name should not affect the the competitor API.

**Comment by PeterJCLaw** [comment]
Note that this is much more a convenience issue for us -- Python is fine with two separate classes that happen to have the same name as long as they're in different places. There is a small benefit to renaming our one though to avoid any confusion, but it _is_ fairly normal to end up with classes with the same name but in different modules.
