### ISSUE TITLE
Add an RC robot for demonstration and explanation

### ISSUE THREAD

**Issue by WillB97** [srobo/competition-simulator#278]
It was suggested at the friendly matches that having a robot that can be manually "driven" by keyboard would be useful for explaining new game mechanics and generally explaining things to teams.

SInce webots contains a Keyboard device for receiving keyboard input in the robot this should be possible to implement in robot code without needing to modify the simulator.

**Comment by PeterJCLaw** [comment]
This is a really cool idea.
I can also see this being useful for the teams themselves to explore ideas.
