### ISSUE TITLE
Consider facading `time` module for easier compatibility with real robot API

### ISSUE THREAD

**Issue by WillB97** [srobo/competition-simulator#341]
The final noticable difference to the physical kit API is the need to use `R.time` and `R.sleep`. We could avoid users needing to use different APIs to the physical kit by overloading `time.time` and `time.sleep`. 

We still need to step the simulator to simulate the execution time, this could be done by adding a forced step to every API call.

**Comment by PeterJCLaw** [comment]
Since the kit API now has `Robot.time` and `Robot.sleep` APIs I propose that we close this as won't-fix.
