### ISSUE TITLE
Marker colours are hard to discern during the videos

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-simulator#385]
See screenshot:
![image](https://user-images.githubusercontent.com/2551763/219870839-6aa57b82-2e8b-4232-9f53-ec9a29c5d8cc.png)
it's hard to tell the difference between bronze and silver tokens

**Comment by Adimote** [comment]
in 360p this is worse
![image](https://user-images.githubusercontent.com/2551763/219871022-345d273e-4a0e-471a-b15e-3a0e5bd95202.png)

**Comment by PeterJCLaw** [comment]
Fixed by #389.
