### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by antoinepetty** [srobo/competition-simulator#44]
The code I've been writing has barely any comments. Would be good to add more for future developers

**Comment by PeterJCLaw** [comment]
@antoinepetty as the person most likely to be able to add such documentation, would you be able to pick this up? It would be great to do this before the next round of development happens on the simulator.

**Comment by antoinepetty** [comment]
I'll see what I can do. Last time I went to look at this it seemed like most of the documentation already existed or was obvious
