### ISSUE TITLE
Reduce camera field of view

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-simulator#446]
It turns out that the field of view of the cameras in the kits is pretty low -- I think 55° was the reported best value, though less than that in most cases. This is a lot lower than the 82° which the simulator currently uses:

https://github.com/srobo/competition-simulator/blob/c2ba7070e62fc309ab5219e3caf3a47a4342d475/protos/Components/SRCamera.proto#L44

We should update the simulator to more closely match the kits.

**Comment by WillB97** [comment]
This is in radians. 0.82 radians is 47 degrees.

**Comment by PeterJCLaw** [comment]
:facepalm:
