### ISSUE TITLE
Validate apparent size/distance of token makers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-simulator#83]
I have a feeling that the vision system may be slightly off in its representation of the size and or distance of the token makers.

The discrepancy originates in the fact that the `MarkerInfo.size` value _should_ be the size of the marker not the token, the former being smaller than the latter by enough to put tape around the marker for the construction of the token.

However the code currently uses only a single value for both concepts. This means that either:
- the size of the maker is misreported
- the size of the token is incorrect

Depending on other interactions, due to the way that the distance to the marker is calculated (relative to the centre of the token), this may also mean that the distance to the marker is misreported.

**Comment by antoinepetty** [comment]
Similar issue being reported on the forum: https://studentrobotics.org/forum/viewtopic.php?f=10&t=110&p=416
But they only mention arena markers? I think it might be because the arena markers are the correct size whereas the token markers fully fit the face (as mentioned above)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne unless we're going to drop vision from SR2021 I think this issue should be considered a blocker. Was it intentional that it be omitted from the SR2021 milesteone?

**Comment by RealOrangeOne** [comment]
Partly that, partly that I had an (apparently false) recollection that we couldn't reliably reproduce this.

**Comment by PeterJCLaw** [comment]
Ah, I'm not sure about reproducibility. This issue was raised based on source analysis, so it's possible that it's a different issue to what was seen in the forums. I think we ought to fix both though :)

**Comment by PeterJCLaw** [comment]
Note: this is only relevant if we are going ahead with using a vision based system for SR2021.

**Comment by PeterJCLaw** [comment]
Blocked: for SR2021 we're not running with a camera, so this isn't relevant this year.
I'm leaving this open however as the camera code is still present and still has this bug. If we go back to having the camera we'll need to fix this.

**Comment by PeterJCLaw** [comment]
SR2023 has a camera again, so this is unblocked.
